export const GET_PRODUCTS_REQUEST = "GET_PRODUCTS_REQUEST";
export const GET_PRODUCTS_SUCCESS = "GET_PRODUCTS_SUCCESS";
export const GET_PRODUCTS_FAIL = "GET_PRODUCTS_FAIL";

export const GET_PRODUCTS_TYPE_SUCCESS = "GET_PRODUCTS_TYPE_SUCCESS";
export const GET_PRODUCTS_TYPE_REQUEST = "GET_PRODUCTS_TYPE_REQUEST";
export const GET_PRODUCTS_TYPE_FAIL = "GET_PRODUCTS_TYPE_FAIL";
